name: Deploy
on:
  workflow_dispatch:

permissions: read-all

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run terraform
        run: |
          terraform init
          terraform apply -auto-approve
